// Code generated by "stringer -type=Op"; DO NOT EDIT.

package tftp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpRead-1]
	_ = x[OpWrite-2]
	_ = x[OpData-3]
	_ = x[OpAck-4]
	_ = x[OpError-5]
}

const _Op_name = "OpReadOpWriteOpDataOpAckOpError"

var _Op_index = [...]uint8{0, 6, 13, 19, 24, 31}

func (i Op) String() string {
	i -= 1
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
